-
  branches:
    only:
      - master
  
  image: Visual Studio 2019
  version: 4.0.0-beta-build.{build}
  configuration: Release

  skip_commits:
    files:
      - docs/*
      
  before_build:
    - dotnet restore
    
  build:
    verbosity: minimal

  artifacts:
    - path: '**\*.nupkg'

  deploy:
    provider: NuGet
    api_key:
      secure: +NAjxjewtZM6YJXeCJPMcy+/Hhon2o1sC3+DfAMbjUbQCdwUvgujce7V+MnLD89Q
    skip_symbols: false
    artifact: /.*\.nupkg/

-
  branches:
    only:
      - development
  
  image: Visual Studio 2019
  version: 4.0.1-beta-build.{build}
  configuration: Release

  skip_commits:
    files:
      - docs/*
      
  before_build:
    - dotnet restore
    
  build:
    verbosity: minimal

  artifacts:
    - path: '**\*.nupkg'
